import { jsPDF } from "jspdf";
import type { Inspection } from "@/types";

const TITLE = "NauticAI Inspection Report";
const MARGIN = 20;
const LINE_HEIGHT = 7;
const FONT_SIZE_NORMAL = 11;
const FONT_SIZE_SMALL = 9;
const FONT_SIZE_HEADING = 16;

function getDetectedClasses(ins: Inspection): string[] {
  const c = ins.detected_classes;
  if (Array.isArray(c)) return c;
  if (typeof c === "string") {
    try {
      const arr = JSON.parse(c) as unknown;
      return Array.isArray(arr) ? arr.map(String) : [];
    } catch {
      return [];
    }
  }
  return [];
}

/** Build the inspection PDF doc (shared for download and viewer). */
function buildInspectionPdfDoc(
  inspection: Inspection,
  annotatedImageDataUrl?: string | null
): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let y = MARGIN;

  doc.setFontSize(FONT_SIZE_HEADING);
  doc.setFont("helvetica", "bold");
  doc.text(TITLE, MARGIN, y);
  y += LINE_HEIGHT + 4;

  doc.setFontSize(FONT_SIZE_NORMAL);
  doc.setFont("helvetica", "normal");
  const id = inspection.inspection_id ?? String(inspection.id);
  const date = inspection.created_at
    ? new Date(inspection.created_at).toLocaleString("en-GB", {
        day: "2-digit",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    : "—";
  const fileName = inspection.file_name ?? "—";
  const riskLevel = inspection.risk_level ?? "—";
  const status = inspection.status ?? "—";

  doc.text(`Inspection ID: ${id}`, MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(`Date: ${date}`, MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(`File: ${fileName}`, MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(`Risk level: ${riskLevel}`, MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(`Status: ${status}`, MARGIN, y);
  y += LINE_HEIGHT + 4;

  const classes = getDetectedClasses(inspection);
  if (classes.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.text("Detected classes", MARGIN, y);
    y += LINE_HEIGHT;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(FONT_SIZE_SMALL);
    classes.forEach((c) => {
      doc.text(`• ${c}`, MARGIN + 4, y);
      y += LINE_HEIGHT;
    });
    doc.setFontSize(FONT_SIZE_NORMAL);
    y += 4;
  }

  const confidence = inspection.highest_confidence;
  if (typeof confidence === "number") {
    doc.text(`Highest confidence: ${(confidence * 100).toFixed(1)}%`, MARGIN, y);
    y += LINE_HEIGHT;
  }
  const inferenceTime = inspection.inference_time;
  if (typeof inferenceTime === "number") {
    doc.text(`Inference time: ${inferenceTime.toFixed(2)} s`, MARGIN, y);
    y += LINE_HEIGHT + 6;
  }

  if (annotatedImageDataUrl && y < 240) {
    try {
      const imgW = 170;
      const imgH = (imgW * 3) / 4;
      if (y + imgH > 270) {
        doc.addPage();
        y = MARGIN;
      }
      doc.setFont("helvetica", "bold");
      doc.text("Annotated image", MARGIN, y);
      y += LINE_HEIGHT;
      doc.addImage(annotatedImageDataUrl, "JPEG", MARGIN, y, imgW, imgH);
      y += imgH + 6;
    } catch {
      // skip image if invalid
    }
  }

  doc.setFontSize(FONT_SIZE_SMALL);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by NauticAI • ${new Date().toISOString().slice(0, 10)}`,
    MARGIN,
    285
  );
  return doc;
}

export function exportInspectionPdf(
  inspection: Inspection,
  annotatedImageDataUrl?: string | null
): void {
  const doc = buildInspectionPdfDoc(inspection, annotatedImageDataUrl);
  const id = inspection.inspection_id ?? String(inspection.id);
  const safeId = id.replace(/[^a-zA-Z0-9-]/g, "_");
  doc.save(`NauticAI-Report-${safeId}.pdf`);
}

/** Return a blob URL for the inspection PDF (for in-app viewer). Caller must revoke the URL when done. */
export function getInspectionPdfBlobUrl(
  inspection: Inspection,
  annotatedImageDataUrl?: string | null
): string {
  const doc = buildInspectionPdfDoc(inspection, annotatedImageDataUrl);
  const blob = doc.output("blob");
  return URL.createObjectURL(blob);
}
